# netlify.toml
[build]
command = "CI=false && npm run build --force"
publish = "build"

[functions]
directory = "netlify/functions"

[dev]
command = "npm start"
port = 3000
targetPort = 3000

# Add redirects for functions
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Add CORS headers for API endpoints
[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Allow-Credentials = "true"